# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Prof. Hyde
description:      'course website template'
url:              http://www.datacarpentry.org/semester-biology
baseurl:          /semester-biology

author:
  name:           'Ethan White & Zack Brym'
  url:            http://weecology.org/

github:
  repo:           https://github.com/datacarpentry/semester-biology
